export { HomePage } from './home';
export { UserPage } from './user';
export { LoginPage, ForgotPasswordPage, LearnerLoginPage } from './auth';
export { LeadPage } from './leads';
export { BranchPage } from './branch';
export { CoursePage } from './course';
export { BatchPage, BatchDetailPage } from './batch';
export { CandidatePage, CandidateFormPage } from './candidate';
export { MyCourseListPage, MyCourseDetailPage } from './myCourses';
export { WhoIam } from './who-i-am';
